# Generated by Django 2.0.6 on 2018-06-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domsapp', '0002_auto_20180629_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='comments',
            field=models.TextField(default='Imprtant'),
        ),
        migrations.AlterField(
            model_name='file',
            name='document',
            field=models.FileField(upload_to=''),
        ),
    ]
