# Generated by Django 2.0.6 on 2018-06-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domsapp', '0004_auto_20180629_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='color',
            field=models.CharField(choices=[('education', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='green', max_length=6),
        ),
    ]
