# Generated by Django 2.0.6 on 2018-06-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domsapp', '0005_file_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='color',
        ),
        migrations.AddField(
            model_name='file',
            name='category',
            field=models.CharField(default='Education', max_length=200),
        ),
    ]
