# Generated by Django 2.0.6 on 2018-06-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domsapp', '0006_auto_20180629_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='document',
            field=models.FileField(upload_to='images/'),
        ),
    ]
