# Generated by Django 2.0.6 on 2018-07-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domsapp', '0007_auto_20180630_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='status',
            field=models.CharField(default='Completed', max_length=200),
        ),
    ]
