# Generated by Django 2.0.6 on 2018-07-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domsapp', '0008_file_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='document',
            field=models.FileField(upload_to=''),
        ),
    ]
